/// <reference path="../hooks/pocketbase-globals.d.ts" />

/**
 * Squashed baseline migration.
 *
 * This single migration creates the complete database schema for the
 * Remix Platform. It replaces all prior incremental migrations that
 * were accumulated during development.
 *
 * Generated from the live PocketBase schema on 2026-09-18.
 */

const collections = [
	{
		"id": "pbc_1990155814",
		"listRule": "question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id)",
		"viewRule": "question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id)",
		"createRule": "",
		"updateRule": null,
		"deleteRule": null,
		"name": "action_logs",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_725520074",
				"help": "",
				"hidden": false,
				"id": "relation1349952704",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "run",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_3458742876",
				"help": "",
				"hidden": false,
				"id": "relation3622292680",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "question",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation2375276105",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "user",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text361630566",
				"max": 100,
				"min": 0,
				"name": "target_id",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"help": "",
				"hidden": false,
				"id": "json2965721996",
				"maxSize": 200000,
				"name": "metadata_json",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "json"
			},
			{
				"help": "",
				"hidden": false,
				"id": "date2277522715",
				"max": "",
				"min": "",
				"name": "occurred_at",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "date"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select4198493223",
				"maxSelect": 1,
				"name": "action_type",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "select",
				"values": [
					"vote_like",
					"vote_repeal",
					"create_solution",
					"remix_solution",
					"merge_solution",
					"comment",
					"focus_enter",
					"focus_exit",
					"vote_migration",
					"migration_dismissed",
					"merge_dismissed",
					"page_view",
					"session_start",
					"tab_switch",
					"create_idea",
					"remix_singular",
					"remix_combine",
					"create_label",
					"subscribe",
					"unsubscribe",
					"ballot_submit",
					"ballot_abstain",
					"compare_open",
					"compare_add",
					"compare_remove",
					"proposal_view",
					"feed_filter_change",
					"hide_proposal",
					"restore_proposal",
					"readiness_signal",
					"notification_panel_open",
					"notification_panel_click",
					"notification_panel_dismiss",
					"push_notification_click",
					"push_notification_dismiss",
					"phase_halfway",
					"phase_ending_soon"
				]
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			}
		],
		"indexes": [
			"CREATE INDEX idx_action_logs_problem_time ON action_logs (`question`, `occurred_at`)",
			"CREATE INDEX idx_action_logs_type ON action_logs (`action_type`)"
		],
		"system": false
	},
	{
		"id": "pbc_ballot_responses",
		"listRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && user = @request.auth.id",
		"viewRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && user = @request.auth.id",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"updateRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && user = @request.auth.id",
		"deleteRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && user = @request.auth.id",
		"name": "ballot_responses",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation2375276105",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "user",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_3458742876",
				"help": "",
				"hidden": false,
				"id": "relation3069659470",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "question",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "json3420889108",
				"maxSize": 0,
				"name": "ranks",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "json"
			}
		],
		"indexes": [
			"CREATE UNIQUE INDEX `idx_ballot_responses_unique` ON `ballot_responses` (`user`, `question`)"
		],
		"system": false
	},
	{
		"id": "pbc_714390402",
		"listRule": "@request.auth.role = 'admin' || @request.auth.id = user || (@collection.group_members.group ?= group && @collection.group_members.user ?= @request.auth.id)",
		"viewRule": "@request.auth.role = 'admin' || @request.auth.id = user || (@collection.group_members.group ?= group && @collection.group_members.user ?= @request.auth.id)",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"updateRule": "@request.auth.role = 'admin' || @collection.groups.id ?= group && @collection.groups.author = @request.auth.id",
		"deleteRule": "@request.auth.role = 'admin' || @request.auth.id = user || (@collection.groups.id ?= group && @collection.groups.author = @request.auth.id)",
		"name": "group_members",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_3346940990",
				"help": "",
				"hidden": false,
				"id": "relation1841317061",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "group",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation2375276105",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "user",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select1466534506",
				"maxSelect": 1,
				"name": "role",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "select",
				"values": [
					"Member",
					"Experimenter",
					"Admin"
				]
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			}
		],
		"indexes": [
			"CREATE UNIQUE INDEX idx_group_members_group_user ON group_members (`group`, `user`)"
		],
		"system": false
	},
	{
		"id": "pbc_3346940990",
		"listRule": "@request.auth.role = 'admin' || author = @request.auth.id || (@collection.group_members.group ?= id && @collection.group_members.user ?= @request.auth.id)",
		"viewRule": "@request.auth.role = 'admin' || author = @request.auth.id || (@collection.group_members.group ?= id && @collection.group_members.user ?= @request.auth.id)",
		"createRule": "@request.auth.role = 'admin' || @request.auth.role = \"admin\"",
		"updateRule": "@request.auth.role = 'admin' || author = @request.auth.id",
		"deleteRule": "@request.auth.role = 'admin' || author = @request.auth.id",
		"name": "groups",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text1579384326",
				"max": 150,
				"min": 1,
				"name": "name",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"convertURLs": false,
				"help": "",
				"hidden": false,
				"id": "editor1843675174",
				"maxSize": 0,
				"name": "description",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "editor"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text1380122564",
				"max": 64,
				"min": 8,
				"name": "invite_token",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"cascadeDelete": false,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation3182418120",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "author",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			}
		],
		"indexes": [
			"CREATE UNIQUE INDEX idx_groups_invite_token ON groups (`invite_token`)"
		],
		"system": false
	},
	{
		"id": "labels_collection_id",
		"listRule": "id != ''",
		"viewRule": "id != ''",
		"createRule": "@request.auth.id != ''",
		"updateRule": null,
		"deleteRule": null,
		"name": "labels",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_3458742876",
				"help": "",
				"hidden": false,
				"id": "lbl_question",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "question",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "lbl_short_name",
				"max": 40,
				"min": 0,
				"name": "short_name",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "lbl_color",
				"max": 0,
				"min": 0,
				"name": "color",
				"pattern": "^#[0-9a-fA-F]{6}$",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"hidden": false,
				"id": "autodate_created",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate_updated",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			}
		],
		"indexes": [
			"CREATE INDEX `idx_labels_question` ON `labels` (`question`)",
			"CREATE UNIQUE INDEX `idx_labels_question_name` ON `labels` (`question`, `short_name`)"
		],
		"system": false
	},
	{
		"id": "post_study_survs",
		"listRule": "@request.auth.role = 'admin' || @request.auth.id = user",
		"viewRule": "@request.auth.role = 'admin' || @request.auth.id = user",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != '' && @request.auth.id = user",
		"updateRule": "@request.auth.role = 'admin' || user = @request.auth.id",
		"deleteRule": null,
		"name": "post_study_surveys",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "user_ref_survey",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "user",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "responses_json",
				"maxSize": 2000000,
				"name": "responses",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "json"
			}
		],
		"indexes": [],
		"system": false
	},
	{
		"id": "dismissals_collection",
		"listRule": "@request.auth.role = 'admin' || @request.auth.id = user",
		"viewRule": "@request.auth.role = 'admin' || @request.auth.id = user",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id = user",
		"updateRule": null,
		"deleteRule": "@request.auth.role = 'admin' || @request.auth.id = user",
		"name": "proposal_hides",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "dsm_user",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "user",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_1857753574",
				"help": "",
				"hidden": false,
				"id": "dsm_proposal",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "proposal",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			}
		],
		"indexes": [
			"CREATE UNIQUE INDEX `idx_dismissals_user_prop` ON `proposal_hides` (\n  `user`,\n  `proposal`\n)"
		],
		"system": false
	},
	{
		"id": "pbc_1554115295",
		"listRule": "@request.auth.role = 'admin' || question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id)",
		"viewRule": "@request.auth.role = 'admin' || question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id)",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"updateRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"deleteRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"name": "proposal_votes",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_1857753574",
				"help": "",
				"hidden": false,
				"id": "relation2670930395",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "proposal",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation2375276105",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "user",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": false,
				"collectionId": "pbc_3458742876",
				"help": "",
				"hidden": false,
				"id": "relation3622292680",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "question",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "date2277522715",
				"max": "",
				"min": "",
				"name": "occurred_at",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "date"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"help": "",
				"hidden": false,
				"id": "number1511032164",
				"max": 1,
				"min": 0,
				"name": "vote",
				"onlyInt": false,
				"presentable": false,
				"required": false,
				"system": false,
				"type": "number"
			}
		],
		"indexes": [
			"CREATE UNIQUE INDEX idx_user_proposal ON proposal_votes (`user`, `proposal`)",
			"CREATE INDEX idx_proposal_votes_proposal ON proposal_votes (`proposal`)"
		],
		"system": false
	},
	{
		"id": "pbc_1857753574",
		"listRule": "@request.auth.role = 'admin' || question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id)",
		"viewRule": "@request.auth.role = 'admin' || question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id)",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"updateRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && author = @request.auth.id",
		"deleteRule": null,
		"name": "proposals",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_3458742876",
				"help": "",
				"hidden": false,
				"id": "relation3622292680",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "question",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": false,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation3182418120",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "author",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text724990059",
				"max": 120,
				"min": 1,
				"name": "title",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text4274335913",
				"max": 200000,
				"min": 1,
				"name": "content",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text3242984672",
				"max": 100,
				"min": 0,
				"name": "reason_for_change",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select2744374011",
				"maxSelect": 1,
				"name": "state",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "select",
				"values": [
					"Proposed",
					"Repealed",
					"Archived",
					"FinalWinner",
					"Deactivated",
					"Inactive",
					"Active"
				]
			},
			{
				"help": "",
				"hidden": false,
				"id": "number185331675",
				"max": 1000000,
				"min": -1000000,
				"name": "current_vote_count",
				"onlyInt": false,
				"presentable": false,
				"required": false,
				"system": false,
				"type": "number"
			},
			{
				"cascadeDelete": false,
				"collectionId": "pbc_1857753574",
				"help": "",
				"hidden": false,
				"id": "relation4225489040",
				"maxSelect": 20,
				"minSelect": 0,
				"name": "parent_proposals",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": false,
				"collectionId": "pbc_1857753574",
				"help": "",
				"hidden": false,
				"id": "relation3832431421",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "root_proposal",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "number2484215358",
				"max": 100000,
				"min": 0,
				"name": "branch_depth",
				"onlyInt": false,
				"presentable": false,
				"required": false,
				"system": false,
				"type": "number"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool3504998576",
				"name": "is_champion",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"help": "",
				"hidden": false,
				"id": "number2002997946",
				"max": null,
				"min": 0,
				"name": "support_count",
				"onlyInt": false,
				"presentable": false,
				"required": false,
				"system": false,
				"type": "number"
			},
			{
				"help": "",
				"hidden": false,
				"id": "number2247008828",
				"max": null,
				"min": 0,
				"name": "opposition_count",
				"onlyInt": false,
				"presentable": false,
				"required": false,
				"system": false,
				"type": "number"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool674583703",
				"name": "in_focus",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"help": "",
				"hidden": false,
				"id": "prop_viewer_cnt",
				"max": null,
				"min": 0,
				"name": "unique_viewer_count",
				"onlyInt": false,
				"presentable": false,
				"required": false,
				"system": false,
				"type": "number"
			},
			{
				"cascadeDelete": false,
				"collectionId": "labels_collection_id",
				"help": "",
				"hidden": false,
				"id": "prop_labels_rel",
				"maxSelect": 2147483647,
				"minSelect": 0,
				"name": "labels",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": false,
				"collectionId": "labels_collection_id",
				"help": "",
				"hidden": false,
				"id": "prop_pr_label_rel",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "primary_label",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "prop_sub_count",
				"max": null,
				"min": 0,
				"name": "subscription_count",
				"onlyInt": false,
				"presentable": false,
				"required": false,
				"system": false,
				"type": "number"
			}
		],
		"indexes": [
			"CREATE INDEX idx_proposals_problem ON proposals (`question`)",
			"CREATE INDEX idx_proposals_author ON proposals (`author`)"
		],
		"system": false
	},
	{
		"id": "pbc_3676117464",
		"listRule": "user = @request.auth.id",
		"viewRule": "user = @request.auth.id",
		"createRule": null,
		"updateRule": "@request.auth.role = 'admin' || user = @request.auth.id",
		"deleteRule": "@request.auth.role = 'admin' || user = @request.auth.id",
		"name": "push_notification_log",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": false,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation_user_log",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "user",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select_event_type",
				"maxSelect": 1,
				"name": "event_type",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "select",
				"values": [
					"vote_migration",
					"phase_change",
					"proposal_remixed",
					"ballot_entry",
					"survey_unlocked",
					"phase_halfway",
					"phase_ending_soon"
				]
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text_reference_id",
				"max": 0,
				"min": 0,
				"name": "reference_id",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select2063623452",
				"maxSelect": 1,
				"name": "status",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "select",
				"values": [
					"pending",
					"actioned",
					"dismissed",
					"sent",
					"failed",
					"expired"
				]
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text966904008",
				"max": 0,
				"min": 0,
				"name": "payload_json",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			}
		],
		"indexes": [],
		"system": false
	},
	{
		"id": "pbc_1438754935",
		"listRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && user = @request.auth.id",
		"viewRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && user = @request.auth.id",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"updateRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && user = @request.auth.id",
		"deleteRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && user = @request.auth.id",
		"name": "push_subscriptions",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": false,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation_user_subs",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "user",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text_endpoint",
				"max": 0,
				"min": 0,
				"name": "endpoint",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text_p256dh",
				"max": 0,
				"min": 0,
				"name": "p256dh",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text_auth",
				"max": 0,
				"min": 0,
				"name": "auth",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text_useragent",
				"max": 0,
				"min": 0,
				"name": "user_agent",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			}
		],
		"indexes": [],
		"system": false
	},
	{
		"id": "pbc_1904111165",
		"listRule": "@request.auth.role = 'admin' || question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id)",
		"viewRule": "@request.auth.role = 'admin' || question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id)",
		"createRule": null,
		"updateRule": null,
		"deleteRule": null,
		"name": "question_phases",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_3458742876",
				"help": "",
				"hidden": false,
				"id": "relation3622292680",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "question",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select2930033448",
				"maxSelect": 1,
				"name": "phase_name",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "select",
				"values": [
					"Proposed",
					"AnswerSearch",
					"Closing",
					"Voting",
					"Decided"
				]
			},
			{
				"help": "",
				"hidden": false,
				"id": "date222754019",
				"max": "",
				"min": "",
				"name": "started_at",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "date"
			},
			{
				"help": "",
				"hidden": false,
				"id": "date473765221",
				"max": "",
				"min": "",
				"name": "ended_at",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "date"
			},
			{
				"cascadeDelete": false,
				"collectionId": "pbc_1904111165",
				"help": "",
				"hidden": false,
				"id": "relation1514483612",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "previous_phase",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text854902533",
				"max": 80,
				"min": 0,
				"name": "transition_type",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"help": "",
				"hidden": false,
				"id": "json2962063901",
				"maxSize": 200000,
				"name": "transition_metadata_json",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "json"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text627304130",
				"max": 100,
				"min": 0,
				"name": "source_record_id",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			}
		],
		"indexes": [
			"CREATE INDEX idx_question_phases_problem_started ON question_phases (`question`, `started_at`)",
			"CREATE INDEX idx_question_phases_problem_ended ON question_phases (`question`, `ended_at`)",
			"CREATE INDEX idx_question_phases_problem_name ON question_phases (`question`, `phase_name`)",
			"CREATE INDEX idx_question_phases_source_record ON question_phases (`source_record_id`)"
		],
		"system": false
	},
	{
		"id": "pbc_548890645",
		"listRule": "@request.auth.role = 'admin' || question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id)",
		"viewRule": "@request.auth.role = 'admin' || question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id)",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"updateRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && user = @request.auth.id",
		"deleteRule": "@request.auth.role = 'admin' || @request.auth.id != \"\" && user = @request.auth.id",
		"name": "question_votes",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_3458742876",
				"help": "",
				"hidden": false,
				"id": "relation3622292680",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "question",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation2375276105",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "user",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "number1511032164",
				"max": 1,
				"min": -1,
				"name": "vote",
				"onlyInt": false,
				"presentable": false,
				"required": true,
				"system": false,
				"type": "number"
			},
			{
				"help": "",
				"hidden": false,
				"id": "date2277522715",
				"max": "",
				"min": "",
				"name": "occurred_at",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "date"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			}
		],
		"indexes": [
			"CREATE UNIQUE INDEX idx_user_problem ON question_votes (`user`, `question`)",
			"CREATE INDEX idx_question_votes_problem ON question_votes (`question`)"
		],
		"system": false
	},
	{
		"id": "pbc_3458742876",
		"listRule": "@request.auth.role = 'admin' || visibility = 'Public' || visibility = '' || author = @request.auth.id || (visibility = 'Group' && @collection.group_members.group ?= group && @collection.group_members.user ?= @request.auth.id)",
		"viewRule": "@request.auth.role = 'admin' || visibility = 'Public' || visibility = '' || author = @request.auth.id || (visibility = 'Group' && @collection.group_members.group ?= group && @collection.group_members.user ?= @request.auth.id)",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"updateRule": null,
		"deleteRule": null,
		"name": "questions",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": false,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation3182418120",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "author",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text724990059",
				"max": 150,
				"min": 5,
				"name": "title",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": false,
				"type": "text"
			},
			{
				"convertURLs": false,
				"help": "",
				"hidden": false,
				"id": "editor1843675174",
				"maxSize": 0,
				"name": "description",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "editor"
			},
			{
				"help": "",
				"hidden": false,
				"id": "json1216616117",
				"maxSize": 200000,
				"name": "constraints",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "json"
			},
			{
				"cascadeDelete": false,
				"collectionId": "pbc_1904111165",
				"help": "",
				"hidden": false,
				"id": "relation363045327",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "current_phase",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "date4180986764",
				"max": "",
				"min": "",
				"name": "discussion_deadline",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "date"
			},
			{
				"help": "",
				"hidden": false,
				"id": "date2443547734",
				"max": "",
				"min": "",
				"name": "closing_window_deadline",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "date"
			},
			{
				"help": "",
				"hidden": false,
				"id": "number2886148443",
				"max": null,
				"min": 0,
				"name": "focus_quorum",
				"onlyInt": false,
				"presentable": false,
				"required": false,
				"system": false,
				"type": "number"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select1368277760",
				"maxSelect": 1,
				"name": "visibility",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "select",
				"values": [
					"Public",
					"Group",
					"Private"
				]
			},
			{
				"cascadeDelete": false,
				"collectionId": "pbc_3346940990",
				"help": "",
				"hidden": false,
				"id": "relation1841317061",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "group",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text1380122564",
				"max": 64,
				"min": 0,
				"name": "invite_token",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select1897859674",
				"maxSelect": 0,
				"name": "current_phase_name",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "select",
				"values": [
					"Proposed",
					"AnswerSearch",
					"Closing",
					"Voting",
					"Decided"
				]
			},
			{
				"help": "",
				"hidden": false,
				"id": "date3285020117",
				"max": "",
				"min": "",
				"name": "vote_deadline",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "date"
			},
			{
				"help": "",
				"hidden": false,
				"id": "json_voting_summary",
				"maxSize": 0,
				"name": "voting_summary_json",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "json"
			},
			{
				"help": "",
				"hidden": false,
				"id": "json3154150053",
				"maxSize": 0,
				"name": "algorithm_config",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "json"
			}
		],
		"indexes": [
			"CREATE UNIQUE INDEX idx_questions_invite_token ON questions (`invite_token`) WHERE `invite_token` != ''"
		],
		"system": false
	},
	{
		"id": "pbc_3769423742",
		"listRule": "@request.auth.role = 'admin' || (@request.auth.id != \"\") && (question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id))",
		"viewRule": "@request.auth.role = 'admin' || (@request.auth.id != \"\") && (question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id))",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"updateRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"deleteRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"name": "simulation_actions",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_725520074",
				"help": "",
				"hidden": false,
				"id": "relation1349952704",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "run",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_3458742876",
				"help": "",
				"hidden": false,
				"id": "relation3622292680",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "question",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": false,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation1148540665",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "actor",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select4198493223",
				"maxSelect": 1,
				"name": "action_type",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "select",
				"values": [
					"createSimUsers",
					"startSimulation",
					"branchSolutions",
					"mergeSolutions",
					"voteProgress",
					"comments",
					"playback",
					"deleteSimulation"
				]
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool2044517703",
				"name": "ok",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "bool"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text1915095946",
				"max": 2000,
				"min": 0,
				"name": "details",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"help": "",
				"hidden": false,
				"id": "json678076018",
				"maxSize": 500000,
				"name": "input_json",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "json"
			},
			{
				"help": "",
				"hidden": false,
				"id": "json4215029259",
				"maxSize": 500000,
				"name": "result_json",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "json"
			},
			{
				"help": "",
				"hidden": false,
				"id": "date2277522715",
				"max": "",
				"min": "",
				"name": "occurred_at",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "date"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			}
		],
		"indexes": [
			"CREATE INDEX idx_sim_actions_run_time ON simulation_actions (`run`, `occurred_at`)",
			"CREATE INDEX idx_sim_actions_problem_time ON simulation_actions (`question`, `occurred_at`)",
			"CREATE INDEX idx_sim_actions_type ON simulation_actions (`action_type`)"
		],
		"system": false
	},
	{
		"id": "pbc_725520074",
		"listRule": "@request.auth.role = 'admin' || (@request.auth.id != \"\") && (question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id))",
		"viewRule": "@request.auth.role = 'admin' || (@request.auth.id != \"\") && (question.visibility = 'Public' || question.visibility = '' || question.author = @request.auth.id || (question.visibility = 'Group' && @collection.group_members.group ?= question.group && @collection.group_members.user ?= @request.auth.id))",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"updateRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"deleteRule": "@request.auth.role = 'admin' || @request.auth.id != \"\"",
		"name": "simulation_runs",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation3479234172",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "owner",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_3458742876",
				"help": "",
				"hidden": false,
				"id": "relation3622292680",
				"maxSelect": 1,
				"minSelect": 1,
				"name": "question",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text245846248",
				"max": 140,
				"min": 0,
				"name": "label",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select2063623452",
				"maxSelect": 1,
				"name": "status",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "select",
				"values": [
					"active",
					"archived"
				]
			},
			{
				"help": "",
				"hidden": false,
				"id": "date222754019",
				"max": "",
				"min": "",
				"name": "started_at",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "date"
			},
			{
				"help": "",
				"hidden": false,
				"id": "date1603515743",
				"max": "",
				"min": "",
				"name": "last_action_at",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "date"
			},
			{
				"help": "",
				"hidden": false,
				"id": "json4171322886",
				"maxSize": 200000,
				"name": "meta_json",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "json"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": true,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": true,
				"type": "autodate"
			}
		],
		"indexes": [
			"CREATE UNIQUE INDEX idx_sim_runs_problem_active_unique ON simulation_runs (`question`) WHERE `status` = \"active\"",
			"CREATE INDEX idx_sim_runs_problem_status ON simulation_runs (`question`, `status`)",
			"CREATE INDEX idx_sim_runs_started_at ON simulation_runs (`started_at`)"
		],
		"system": false
	},
	{
		"id": "pbc_2193141113",
		"listRule": "@request.auth.role = 'admin' || user = @request.auth.id",
		"viewRule": "@request.auth.role = 'admin' || user = @request.auth.id",
		"createRule": "@request.auth.role = 'admin' || @request.auth.id != ''",
		"updateRule": null,
		"deleteRule": null,
		"name": "study_consents",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": false,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "relation2375276105",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "user",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select1582905952",
				"maxSelect": 1,
				"name": "method",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "select",
				"values": [
					"A",
					"B"
				]
			},
			{
				"help": "",
				"hidden": false,
				"id": "date2616989997",
				"max": "",
				"min": "",
				"name": "consented_at",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "date"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool434711658",
				"name": "results_opt_in",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"exceptDomains": null,
				"help": "",
				"hidden": false,
				"id": "email2166945884",
				"name": "results_email",
				"onlyDomains": null,
				"presentable": false,
				"required": false,
				"system": false,
				"type": "email"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": false,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": false,
				"type": "autodate"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool_consent_1",
				"name": "consent_1",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool_consent_2",
				"name": "consent_2",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool_consent_3",
				"name": "consent_3",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool_consent_4",
				"name": "consent_4",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool_consent_screen",
				"name": "consent_screen",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool_consent_stop",
				"name": "consent_stop",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool_consent_final",
				"name": "consent_final",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			}
		],
		"indexes": [],
		"system": false
	},
	{
		"id": "user_prop_views",
		"listRule": "@request.auth.id = user || @request.auth.role = 'admin'",
		"viewRule": "@request.auth.id = user || @request.auth.role = 'admin'",
		"createRule": null,
		"updateRule": null,
		"deleteRule": null,
		"name": "user_proposal_views",
		"type": "base",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cascadeDelete": true,
				"collectionId": "_pb_users_auth_",
				"help": "",
				"hidden": false,
				"id": "upv_user_ref",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "user",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_1857753574",
				"help": "",
				"hidden": false,
				"id": "upv_prop_ref",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "proposal",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"cascadeDelete": true,
				"collectionId": "pbc_3458742876",
				"help": "",
				"hidden": false,
				"id": "upv_quest_ref",
				"maxSelect": 1,
				"minSelect": 0,
				"name": "question",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "relation"
			},
			{
				"help": "",
				"hidden": false,
				"id": "upv_first_view",
				"max": "",
				"min": "",
				"name": "first_viewed",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "date"
			},
			{
				"help": "",
				"hidden": false,
				"id": "upv_last_view",
				"max": "",
				"min": "",
				"name": "last_viewed",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "date"
			},
			{
				"help": "",
				"hidden": false,
				"id": "upv_view_count",
				"max": null,
				"min": 1,
				"name": "view_count",
				"onlyInt": false,
				"presentable": false,
				"required": true,
				"system": false,
				"type": "number"
			}
		],
		"indexes": [
			"CREATE UNIQUE INDEX `idx_upv_user_proposal` ON `user_proposal_views` (`user`, `proposal`)"
		],
		"system": false
	},
	{
		"id": "_pb_users_auth_",
		"listRule": "",
		"viewRule": "",
		"createRule": "",
		"updateRule": "id = @request.auth.id",
		"deleteRule": "id = @request.auth.id",
		"name": "users",
		"type": "auth",
		"fields": [
			{
				"autogeneratePattern": "[a-z0-9]{15}",
				"help": "",
				"hidden": false,
				"id": "text3208210256",
				"max": 15,
				"min": 15,
				"name": "id",
				"pattern": "^[a-z0-9]+$",
				"presentable": false,
				"primaryKey": true,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"cost": 0,
				"help": "",
				"hidden": true,
				"id": "password901924565",
				"max": 0,
				"min": 8,
				"name": "password",
				"pattern": "",
				"presentable": false,
				"required": true,
				"system": true,
				"type": "password"
			},
			{
				"autogeneratePattern": "[a-zA-Z0-9]{50}",
				"help": "",
				"hidden": true,
				"id": "text2504183744",
				"max": 60,
				"min": 30,
				"name": "tokenKey",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": true,
				"system": true,
				"type": "text"
			},
			{
				"exceptDomains": null,
				"help": "",
				"hidden": false,
				"id": "email3885137012",
				"name": "email",
				"onlyDomains": null,
				"presentable": false,
				"required": true,
				"system": true,
				"type": "email"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool1547992806",
				"name": "emailVisibility",
				"presentable": false,
				"required": false,
				"system": true,
				"type": "bool"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool256245529",
				"name": "verified",
				"presentable": false,
				"required": false,
				"system": true,
				"type": "bool"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text1579384326",
				"max": 255,
				"min": 0,
				"name": "name",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"help": "",
				"hidden": false,
				"id": "file376926767",
				"maxSelect": 1,
				"maxSize": 0,
				"mimeTypes": [
					"image/jpeg",
					"image/png",
					"image/svg+xml",
					"image/gif",
					"image/webp"
				],
				"name": "avatar",
				"presentable": false,
				"protected": false,
				"required": false,
				"system": false,
				"thumbs": null,
				"type": "file"
			},
			{
				"hidden": false,
				"id": "autodate2990389176",
				"name": "created",
				"onCreate": true,
				"onUpdate": false,
				"presentable": false,
				"system": false,
				"type": "autodate"
			},
			{
				"hidden": false,
				"id": "autodate3332085495",
				"name": "updated",
				"onCreate": true,
				"onUpdate": true,
				"presentable": false,
				"system": false,
				"type": "autodate"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool3420079739",
				"name": "simulation",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text1374008987",
				"max": 2000,
				"min": 0,
				"name": "persona",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"help": "",
				"hidden": false,
				"id": "select_user_role",
				"maxSelect": 1,
				"name": "role",
				"presentable": false,
				"required": true,
				"system": false,
				"type": "select",
				"values": [
					"admin",
					"participant"
				]
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text_language_fld",
				"max": 0,
				"min": 0,
				"name": "language",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool1982874466",
				"name": "has_consented",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			},
			{
				"autogeneratePattern": "",
				"help": "",
				"hidden": false,
				"id": "text_user_agent",
				"max": 0,
				"min": 0,
				"name": "user_agent",
				"pattern": "",
				"presentable": false,
				"primaryKey": false,
				"required": false,
				"system": false,
				"type": "text"
			},
			{
				"help": "",
				"hidden": false,
				"id": "bool665483166",
				"name": "has_seen_onboarding",
				"presentable": false,
				"required": false,
				"system": false,
				"type": "bool"
			}
		],
		"indexes": [
			"CREATE UNIQUE INDEX `idx_tokenKey__pb_users_auth_` ON `users` (`tokenKey`)",
			"CREATE UNIQUE INDEX `idx_email__pb_users_auth_` ON `users` (`email`) WHERE `email` != ''"
		],
		"system": false,
		"authRule": "",
		"manageRule": null,
		"authAlert": {
			"enabled": true,
			"emailTemplate": {
				"subject": "Login from a new location",
				"body": "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
			}
		},
		"oauth2": {
			"providers": [],
			"mappedFields": {
				"id": "",
				"name": "name",
				"username": "",
				"avatarURL": "avatar"
			},
			"enabled": false
		},
		"passwordAuth": {
			"enabled": true,
			"identityFields": [
				"email"
			]
		},
		"mfa": {
			"enabled": false,
			"duration": 1800,
			"rule": ""
		},
		"otp": {
			"enabled": false,
			"duration": 180,
			"length": 8,
			"emailTemplate": {
				"subject": "OTP for {APP_NAME}",
				"body": "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
			}
		},
		"authToken": {
			"duration": 604800
		},
		"passwordResetToken": {
			"duration": 1800
		},
		"emailChangeToken": {
			"duration": 1800
		},
		"verificationToken": {
			"duration": 259200
		},
		"fileToken": {
			"duration": 180
		},
		"verificationTemplate": {
			"subject": "Verify your {APP_NAME} email",
			"body": "<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
		},
		"resetPasswordTemplate": {
			"subject": "Reset your {APP_NAME} password",
			"body": "<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Reset password</a>\n</p>\n<p><i>If you didn't ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
		},
		"confirmEmailChangeTemplate": {
			"subject": "Confirm your {APP_NAME} new email address",
			"body": "<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Confirm new email</a>\n</p>\n<p><i>If you didn't ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>"
		}
	}
] as const;

migrate(
	(app) => {
		app.importCollections(collections, false);
	},
	(app) => {
		// Down migration: delete all application collections in reverse order.
		const names = collections.map((c: any) => c.name).reverse();
		for (const name of names) {
			try {
				const col = app.findCollectionByNameOrId(name);
				app.delete(col);
			} catch (_) {}
		}
	}
);
